name: Push dev branch container to ghcr

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  dev-build-and-push:
    runs-on: [self-hosted, linux, x64]
    steps:
        - uses: actions/checkout@v4
        - name: Build the Docker image
          run: |
            buildx_containers=$(docker container ls -qf "name=buildx_buildkit")
            buildx_volumes=$(docker volume ls -qf "name=buildx_buildkit")

            if [ -n "$buildx_containers" ]; then
              echo "Buildx containers to delete: " "$buildx_containers"
              docker container rm -f "$buildx_containers"
            fi

            if [ -n "$buildx_volumes" ]; then
              echo "Buildx volumes to delete: " "$buildx_volumes"
              docker volume rm "$buildx_volumes"
            fi

            # Create build container
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --use

            # Authenticate on registries
            docker login https://ghcr.io -u qdrant --password ${{ secrets.GITHUB_TOKEN }}

            # Build regular image for Github Registry
            GITHUB_TAG="-t ghcr.io/qdrant/qdrant:dev-${{ github.sha }} -t ghcr.io/qdrant/qdrant:dev"

            # Pull, retag and push to GitHub packages
            docker buildx build --platform='linux/amd64,linux/arm64' --build-arg GIT_COMMIT_ID=${{ github.sha }} $GITHUB_TAG --push --label "org.opencontainers.image.revision"=${{ github.sha }} .


